from app.models.program_studi import ProgramStudi
from app.models.role import Role
from app.models.user import User
from app.models.lkps import (
    LkpsTemplate,
    LkpsSubmission,
    LkpsSectionProgress,
    LkpsVmts,
    LkpsKerjasama,
    LkpsPenggunaanDana,
    LkpsKurikulum,
    LkpsIntegrasiPenelitian,
    LkpsMkBasicScience,
    LkpsCapstoneDesign,
    LkpsPenelitianSummary,
    LkpsPkmSummary,
    LkpsDosenProfil,
    LkpsTenagaKependidikan,
    LkpsBebanKerjaDosen,
    LkpsPublikasiIlmiah,
    LkpsLuaranPenelitian,
    LkpsProdukJasa,
    LkpsKinerjaDtps,
    LkpsSitasiDtps,
    LkpsRekognisiDtps,
    LkpsPembimbingLapangan,
    LkpsPrasarana,
    LkpsK3lDokumen,
    LkpsK3lFasilitas,
    LkpsMahasiswaAktif,
    LkpsIpkLulusan,
    LkpsPrestasiMahasiswa,
    LkpsMasaStudi,
    LkpsWaktuTunggu,
    LkpsKesesuaianKerja,
    LkpsTempatKerja,
    LkpsKepuasanPengguna,
    LkpsPenelitianMahasiswa,
    LkpsSpmiDokumen,
    LkpsSpmiPelaksanaan,
)

__all__ = [
    "ProgramStudi", "Role", "User",
    "LkpsTemplate", "LkpsSubmission", "LkpsSectionProgress",
    "LkpsVmts", "LkpsKerjasama", "LkpsPenggunaanDana",
    "LkpsKurikulum", "LkpsIntegrasiPenelitian", "LkpsMkBasicScience",
    "LkpsCapstoneDesign", "LkpsPenelitianSummary", "LkpsPkmSummary",
    "LkpsDosenProfil", "LkpsTenagaKependidikan", "LkpsBebanKerjaDosen",
    "LkpsPublikasiIlmiah", "LkpsLuaranPenelitian", "LkpsProdukJasa",
    "LkpsKinerjaDtps", "LkpsSitasiDtps", "LkpsRekognisiDtps",
    "LkpsPembimbingLapangan", "LkpsPrasarana", "LkpsK3lDokumen", "LkpsK3lFasilitas",
    "LkpsMahasiswaAktif", "LkpsIpkLulusan", "LkpsPrestasiMahasiswa", "LkpsMasaStudi",
    "LkpsWaktuTunggu", "LkpsKesesuaianKerja", "LkpsTempatKerja", "LkpsKepuasanPengguna",
    "LkpsPenelitianMahasiswa", "LkpsSpmiDokumen", "LkpsSpmiPelaksanaan",
]
