from app.models.data_lkps import DataLKPS
from app.models.evidence import Evidence, EvidenceIndikator, EvidenceProdi
from app.models.indikator import Indikator
from app.models.kriteria import Kriteria
from app.models.lkps import (
    LkpsBebanKerjaDosen,
    LkpsCapstoneDesign,
    LkpsDosenProfil,
    LkpsIntegrasiPenelitian,
    LkpsIpkLulusan,
    LkpsK3lDokumen,
    LkpsK3lFasilitas,
    LkpsKepuasanPengguna,
    LkpsKerjasama,
    LkpsKesesuaianKerja,
    LkpsKinerjaDtps,
    LkpsKurikulum,
    LkpsLuaranPenelitian,
    LkpsMahasiswaAktif,
    LkpsMasaStudi,
    LkpsMkBasicScience,
    LkpsPembimbingLapangan,
    LkpsPenelitianMahasiswa,
    LkpsPenelitianSummary,
    LkpsPenggunaanDana,
    LkpsPkmSummary,
    LkpsPrasarana,
    LkpsPrestasiMahasiswa,
    LkpsProdukJasa,
    LkpsPublikasiIlmiah,
    LkpsRekognisiDtps,
    LkpsSectionProgress,
    LkpsSitasiDtps,
    LkpsSpmiDokumen,
    LkpsSpmiPelaksanaan,
    LkpsSubmission,
    LkpsTempatKerja,
    LkpsTemplate,
    LkpsTenagaKependidikan,
    LkpsVmts,
    LkpsWaktuTunggu,
)
from app.models.narasi_led import NarasiLED
from app.models.program_studi import ProgramStudi
from app.models.role import Role
from app.models.simulasi import IndikatorSimulasi, KomponenPenilaian, MatriksAkreditasi
from app.models.target_akreditasi import TargetAkreditasi
from app.models.user import User

__all__ = [
    "ProgramStudi",
    "Role",
    "User",
    "Kriteria",
    "Indikator",
    "TargetAkreditasi",
    "Evidence",
    "EvidenceProdi",
    "EvidenceIndikator",
    "DataLKPS",
    "NarasiLED",
    "MatriksAkreditasi",
    "KomponenPenilaian",
    "IndikatorSimulasi",
    "LkpsTemplate",
    "LkpsSubmission",
    "LkpsSectionProgress",
    "LkpsVmts",
    "LkpsKerjasama",
    "LkpsPenggunaanDana",
    "LkpsKurikulum",
    "LkpsIntegrasiPenelitian",
    "LkpsMkBasicScience",
    "LkpsCapstoneDesign",
    "LkpsPenelitianSummary",
    "LkpsPkmSummary",
    "LkpsDosenProfil",
    "LkpsTenagaKependidikan",
    "LkpsBebanKerjaDosen",
    "LkpsPublikasiIlmiah",
    "LkpsLuaranPenelitian",
    "LkpsProdukJasa",
    "LkpsKinerjaDtps",
    "LkpsSitasiDtps",
    "LkpsRekognisiDtps",
    "LkpsPembimbingLapangan",
    "LkpsPrasarana",
    "LkpsK3lDokumen",
    "LkpsK3lFasilitas",
    "LkpsMahasiswaAktif",
    "LkpsIpkLulusan",
    "LkpsPrestasiMahasiswa",
    "LkpsMasaStudi",
    "LkpsWaktuTunggu",
    "LkpsKesesuaianKerja",
    "LkpsTempatKerja",
    "LkpsKepuasanPengguna",
    "LkpsPenelitianMahasiswa",
    "LkpsSpmiDokumen",
    "LkpsSpmiPelaksanaan",
]
