import type { FieldDefinition, SectionDefinition } from "@/types/lkps";

const vmtsFields: FieldDefinition[] = [
  { key: "no", label: "No", type: "integer", span: 1 },
  {
    key: "jenis_vmts",
    label: "Jenis VMTS",
    type: "select",
    options: [
      { label: "VMTS PT", value: "VMTS PT" },
      { label: "VMTS UPPS", value: "VMTS UPPS" },
      { label: "Visi Keilmuan PS", value: "Visi Keilmuan PS" },
    ],
  },
  { key: "pernyataan", label: "Pernyataan", type: "textarea", span: 2 },
  { key: "no_sk", label: "Nomor SK", type: "text" },
  { key: "link_dokumen", label: "Link Dokumen", type: "text" },
];

const pppiDisiplinFields: FieldDefinition[] = [
  { key: "no", label: "No", type: "integer" },
  { key: "disiplin", label: "Disiplin Teknik Keinsinyuran", type: "text", span: 2 },
  { key: "diselenggarakan", label: "Diselenggarakan", type: "boolean" },
];

const kerjasamaFields: FieldDefinition[] = [
  { key: "lembaga_mitra", label: "Lembaga Mitra", type: "text", span: 2 },
  {
    key: "tingkat",
    label: "Tingkat",
    type: "select",
    options: [
      { label: "Internasional", value: "internasional" },
      { label: "Nasional", value: "nasional" },
      { label: "Lokal", value: "lokal" },
    ],
  },
  { key: "judul_kegiatan", label: "Judul Kegiatan", type: "textarea", span: 2 },
  { key: "manfaat", label: "Manfaat", type: "textarea", span: 2 },
  { key: "tanggal_awal", label: "Tanggal Mulai", type: "date" },
  { key: "tanggal_akhir", label: "Tanggal Selesai", type: "date" },
  { key: "bukti_kerjasama", label: "Bukti Kerjasama", type: "text", span: 2 },
];

const penggunaanDanaFields: FieldDefinition[] = [
  { key: "kode", label: "Jenis Penggunaan", type: "text" },
  { key: "upps_ts2", label: "UPPS TS-2", type: "integer" },
  { key: "upps_ts1", label: "UPPS TS-1", type: "integer" },
  { key: "upps_ts", label: "UPPS TS", type: "integer" },
  { key: "ps_ts2", label: "PS TS-2", type: "integer" },
  { key: "ps_ts1", label: "PS TS-1", type: "integer" },
  { key: "ps_ts", label: "PS TS", type: "integer" },
];

const kurikulumFields: FieldDefinition[] = [
  { key: "no", label: "No", type: "integer" },
  { key: "semester", label: "Semester", type: "integer" },
  { key: "kode_mk", label: "Kode MK", type: "text" },
  { key: "nama_mk", label: "Nama MK", type: "text", span: 2 },
  { key: "kompetensi", label: "Kompetensi", type: "textarea", span: 2 },
  { key: "sks_kuliah", label: "SKS Kuliah", type: "decimal", step: 0.5 },
  { key: "sks_seminar", label: "SKS Seminar", type: "decimal", step: 0.5 },
  { key: "sks_praktikum", label: "SKS Praktikum", type: "decimal", step: 0.5 },
  { key: "konversi_jam", label: "Konversi Jam", type: "decimal", step: 0.5 },
  { key: "dokumen_rps", label: "Link RPS", type: "text" },
  { key: "unit_penyelenggara", label: "Unit Penyelenggara", type: "text" },
];

const mataKuliahPpiFields: FieldDefinition[] = [
  { key: "no", label: "No", type: "integer" },
  { key: "mata_kuliah", label: "Mata Kuliah", type: "text", span: 2 },
  { key: "bobot_sks", label: "Bobot (SKS)", type: "decimal", step: 0.5 },
  { key: "konversi_teori_jam", label: "Teori (Jam)", type: "decimal", step: 0.5 },
  { key: "konversi_praktik_jam", label: "Praktik (Jam)", type: "decimal", step: 0.5 },
  { key: "dokumen_rps", label: "Dokumen RPS", type: "text", span: 2 },
];

const integrasiPenelitianFields: FieldDefinition[] = [
  { key: "nama_dosen", label: "Nama Dosen", type: "text", span: 2 },
  { key: "judul_penelitian_pkm", label: "Judul Penelitian/PkM", type: "textarea", span: 2 },
  { key: "mata_kuliah", label: "Mata Kuliah", type: "text", span: 2 },
  { key: "bentuk_integrasi", label: "Bentuk Integrasi", type: "text", span: 2 },
  { key: "tahun_ts2", label: "TS-2", type: "boolean" },
  { key: "tahun_ts1", label: "TS-1", type: "boolean" },
  { key: "tahun_ts", label: "TS", type: "boolean" },
  {
    key: "kesesuaian_peta_jalan",
    label: "Kesesuaian Peta Jalan",
    type: "select",
    options: [
      { label: "Sesuai", value: "Sesuai" },
      { label: "Tidak Sesuai", value: "Tidak Sesuai" },
    ],
  },
  { key: "bukti_sahih", label: "Bukti", type: "text", span: 2 },
  { key: "kesesuaian_rps", label: "Kesesuaian RPS", type: "text" },
];

const basicScienceFields: FieldDefinition[] = [
  { key: "no", label: "No", type: "integer" },
  { key: "nama_mk", label: "Nama MK", type: "text", span: 2 },
  { key: "semester", label: "Semester", type: "integer" },
  { key: "jumlah_sks", label: "Jumlah SKS", type: "decimal", step: 0.5 },
];

const capstoneFields: FieldDefinition[] = [
  { key: "no", label: "No", type: "integer" },
  { key: "nama_mk_pendukung", label: "MK Pendukung", type: "text", span: 2 },
  { key: "sks_pendukung", label: "SKS Pendukung", type: "decimal", step: 0.5 },
  { key: "nama_mk_capstone", label: "MK Capstone", type: "text", span: 2 },
  { key: "sks_capstone", label: "SKS Capstone", type: "decimal", step: 0.5 },
  { key: "semester", label: "Semester", type: "integer" },
  { key: "cakupan_bahasan", label: "Cakupan Bahasan", type: "textarea", span: 2 },
];

const aggregateSummaryFields: FieldDefinition[] = [
  { key: "kode_sumber", label: "Kode Sumber", type: "text" },
  { key: "ts2", label: "TS-2", type: "integer" },
  { key: "ts1", label: "TS-1", type: "integer" },
  { key: "ts", label: "TS", type: "integer" },
];

const dosenProfilFields: FieldDefinition[] = [
  { key: "no", label: "No", type: "integer" },
  { key: "nama_dosen", label: "Nama Dosen", type: "text", span: 2 },
  { key: "nidn_nidk", label: "NIDN/NIDK", type: "text" },
  { key: "kategori", label: "Kategori", type: "text" },
  { key: "bidang_keahlian", label: "Bidang Keahlian", type: "text", span: 2 },
  { key: "jabatan_akademik", label: "Jabatan Akademik", type: "text" },
  { key: "no_sertifikat_pendidik", label: "No. Sertifikat", type: "text" },
];

const tendikFields: FieldDefinition[] = [
  { key: "no", label: "No", type: "integer" },
  { key: "nama", label: "Nama", type: "text", span: 2 },
  { key: "pendidikan_terakhir", label: "Pendidikan", type: "text" },
  { key: "sertifikat_kompetensi", label: "Sertifikat", type: "text", span: 2 },
  { key: "unit_kerja", label: "Unit Kerja", type: "text" },
];

const bebanKerjaFields: FieldDefinition[] = [
  { key: "no", label: "No", type: "integer" },
  { key: "nama_dosen", label: "Nama Dosen", type: "text", span: 2 },
  { key: "dtps", label: "DTPS", type: "boolean" },
  { key: "bk_ps_diakreditasi", label: "BK PS Diakreditasi", type: "decimal", step: 0.5 },
  { key: "bk_ps_lain_pt", label: "BK PS Lain PT", type: "decimal", step: 0.5 },
  { key: "bk_ps_luar_pt", label: "BK PS Luar PT", type: "decimal", step: 0.5 },
  { key: "bk_penelitian", label: "BK Penelitian", type: "decimal", step: 0.5 },
  { key: "bk_pkm", label: "BK PkM", type: "decimal", step: 0.5 },
  { key: "bk_tugas_tambahan", label: "BK Tugas Tambahan", type: "decimal", step: 0.5 },
];

const publikasiFields: FieldDefinition[] = [
  { key: "kode_publikasi", label: "Kode", type: "text" },
  { key: "ts2", label: "TS-2", type: "integer" },
  { key: "ts1", label: "TS-1", type: "integer" },
  { key: "ts", label: "TS", type: "integer" },
];

const luaranFields: FieldDefinition[] = [
  { key: "judul", label: "Judul / Deskripsi", type: "textarea", span: 2 },
  { key: "tanggal", label: "Tanggal", type: "date" },
  { key: "nomor_paten", label: "Nomor Paten", type: "text" },
  { key: "nomor_hki", label: "Nomor HKI", type: "text" },
  { key: "status_tkt", label: "Status TKT", type: "text" },
  { key: "nomor_sertifikat_tkt", label: "No Sertifikat TKT", type: "text" },
  { key: "nomor_isbn", label: "Nomor ISBN", type: "text" },
  { key: "status_mahasiswa", label: "Status Mahasiswa", type: "text" },
  { key: "keterangan", label: "Keterangan", type: "textarea", span: 2 },
];

const produkJasaFields: FieldDefinition[] = [
  { key: "nama_pembuat", label: "Nama Pembuat", type: "text", span: 2 },
  { key: "nama_produk_jasa", label: "Produk/Jasa", type: "text", span: 2 },
  { key: "deskripsi", label: "Deskripsi", type: "textarea", span: 2 },
  { key: "bukti", label: "Bukti", type: "text", span: 2 },
];

const rekognisiFields: FieldDefinition[] = [
  { key: "no", label: "No", type: "integer" },
  { key: "nama_dosen", label: "Nama Dosen", type: "text", span: 2 },
  { key: "rekognisi", label: "Rekognisi", type: "textarea", span: 2 },
  { key: "tingkat", label: "Tingkat", type: "text" },
  { key: "tahun", label: "Tahun", type: "integer" },
  { key: "bukti_pendukung", label: "Bukti", type: "text", span: 2 },
];

const pembimbingFields: FieldDefinition[] = [
  { key: "no", label: "No", type: "integer" },
  { key: "nama", label: "Nama", type: "text", span: 2 },
  { key: "industri", label: "Industri", type: "text", span: 2 },
  { key: "bidang_keinsinyuran", label: "Bidang", type: "text", span: 2 },
  { key: "pengalaman_kerja_tahun", label: "Pengalaman (th)", type: "integer" },
  { key: "pendidikan_tinggi", label: "Pendidikan", type: "text" },
  { key: "kategori_sip", label: "Kategori SIP", type: "text" },
  { key: "nomor_sip", label: "Nomor SIP", type: "text" },
  { key: "tanggal_berakhir_sip", label: "Tanggal Berakhir", type: "date" },
  { key: "jumlah_bimbingan_3tahun", label: "Jumlah Bimbingan (3 th)", type: "integer" },
];

const prasaranaFields: FieldDefinition[] = [
  { key: "no", label: "No", type: "integer" },
  { key: "nama_prasarana", label: "Nama Prasarana", type: "text", span: 2 },
  { key: "jumlah_prasarana", label: "Jumlah Prasarana", type: "integer" },
  { key: "nama_sarana", label: "Nama Sarana", type: "text", span: 2 },
  { key: "jumlah_standar_minimal", label: "Standar Minimal", type: "integer" },
  { key: "jumlah_dimiliki", label: "Jumlah Dimiliki", type: "integer" },
  { key: "kepemilikan", label: "Kepemilikan", type: "text" },
  { key: "kondisi", label: "Kondisi", type: "text" },
  { key: "logbook", label: "Logbook", type: "text" },
];

const k3lDokumenFields: FieldDefinition[] = [
  { key: "no", label: "No", type: "integer" },
  { key: "jenis_dokumen", label: "Jenis Dokumen", type: "text", span: 2 },
  { key: "jumlah", label: "Jumlah", type: "integer" },
  { key: "riwayat_pengesahan", label: "Riwayat Pengesahan", type: "textarea", span: 2 },
];

const k3lFasilitasFields: FieldDefinition[] = [
  { key: "no", label: "No", type: "integer" },
  { key: "nama_sarana", label: "Nama Sarana", type: "text", span: 2 },
  { key: "fungsi", label: "Fungsi", type: "text", span: 2 },
  { key: "jumlah_unit", label: "Jumlah Unit", type: "integer" },
  { key: "kondisi", label: "Kondisi", type: "text" },
];

const mahasiswaAktifFields: FieldDefinition[] = [
  { key: "no", label: "No", type: "integer" },
  { key: "program_studi_nama", label: "Program Studi", type: "text", span: 2 },
  { key: "prodi_diakreditasi", label: "PS Diakreditasi", type: "boolean" },
  { key: "aktif_ts2", label: "Aktif TS-2", type: "integer" },
  { key: "aktif_ts1", label: "Aktif TS-1", type: "integer" },
  { key: "aktif_ts", label: "Aktif TS", type: "integer" },
  { key: "asing_fulltime_ts2", label: "Asing Fulltime TS-2", type: "integer" },
  { key: "asing_fulltime_ts1", label: "Asing Fulltime TS-1", type: "integer" },
  { key: "asing_fulltime_ts", label: "Asing Fulltime TS", type: "integer" },
  { key: "asing_parttime_ts2", label: "Asing Parttime TS-2", type: "integer" },
  { key: "asing_parttime_ts1", label: "Asing Parttime TS-1", type: "integer" },
  { key: "asing_parttime_ts", label: "Asing Parttime TS", type: "integer" },
];

const _tsPeriodeOptions = [
  { value: "TS-2", label: "TS-2" },
  { value: "TS-1", label: "TS-1" },
  { value: "TS", label: "TS" },
];

const _jenisProgramOptions = [
  { value: "D1", label: "Diploma 1" },
  { value: "D2", label: "Diploma 2" },
  { value: "D3", label: "Diploma 3" },
  { value: "S1", label: "Sarjana (S1)" },
  { value: "S1Tr", label: "Sarjana Terapan" },
  { value: "S2", label: "Magister (S2)" },
  { value: "S2Tr", label: "Magister Terapan" },
  { value: "S3", label: "Doktor (S3)" },
  { value: "S3Tr", label: "Doktor Terapan" },
  { value: "PPI", label: "Profesi Insinyur" },
];

const ipkFields: FieldDefinition[] = [
  { key: "periode", label: "Periode", type: "select", options: _tsPeriodeOptions },
  { key: "jumlah_lulusan", label: "Jumlah Lulusan", type: "integer" },
  { key: "ipk_min", label: "IPK Minimum", type: "decimal", step: 0.01 },
  { key: "ipk_rata", label: "IPK Rata-Rata", type: "decimal", step: 0.01 },
  { key: "ipk_maks", label: "IPK Maksimum", type: "decimal", step: 0.01 },
];

const prestasiFields: FieldDefinition[] = [
  { key: "no", label: "No", type: "integer" },
  { key: "nama_kegiatan", label: "Nama Kegiatan", type: "text", span: 2 },
  { key: "waktu_perolehan", label: "Tanggal", type: "date" },
  { key: "tingkat", label: "Tingkat", type: "text" },
  { key: "prestasi_dicapai", label: "Prestasi", type: "textarea", span: 2 },
];

const masaStudiFields: FieldDefinition[] = [
  { key: "jenis_program", label: "Jenis Program", type: "select", options: _jenisProgramOptions },
  { key: "tahun_masuk", label: "Tahun Masuk", type: "text" },
  { key: "jumlah_masuk", label: "Jumlah Masuk", type: "integer" },
  { key: "jumlah_lulus_tepat_waktu", label: "Lulus Tepat Waktu", type: "integer" },
  { key: "jumlah_lulus_terlambat", label: "Lulus Terlambat", type: "integer" },
  { key: "jumlah_tidak_lulus", label: "Tidak Lulus", type: "integer" },
];

const waktuTungguFields: FieldDefinition[] = [
  { key: "jenis_program", label: "Jenis Program", type: "select", options: _jenisProgramOptions },
  { key: "tahun_lulus", label: "Tahun Lulus", type: "select", options: _tsPeriodeOptions },
  { key: "jumlah_lulusan", label: "Jumlah Lulusan", type: "integer" },
  { key: "jumlah_terlacak", label: "Jumlah Terlacak", type: "integer" },
  { key: "jumlah_dipesan_sebelum_lulus", label: "Dipesan Sebelum Lulus", type: "integer" },
  { key: "wt_lt_3bulan", label: "< 3 Bulan", type: "integer" },
  { key: "wt_3_6bulan", label: "3-6 Bulan", type: "integer" },
  { key: "wt_gt_6bulan", label: "> 6 Bulan", type: "integer" },
];

const kesesuaianKerjaFields: FieldDefinition[] = [
  { key: "tahun_lulus", label: "Tahun Lulus", type: "select", options: _tsPeriodeOptions },
  { key: "jumlah_lulusan", label: "Jumlah Lulusan", type: "integer" },
  { key: "jumlah_terlacak", label: "Jumlah Terlacak", type: "integer" },
  { key: "kesesuaian_rendah", label: "Rendah", type: "integer" },
  { key: "kesesuaian_sedang", label: "Sedang", type: "integer" },
  { key: "kesesuaian_tinggi", label: "Tinggi", type: "integer" },
];

const tempatKerjaFields: FieldDefinition[] = [
  { key: "tahun_lulus", label: "Tahun Lulus", type: "select", options: _tsPeriodeOptions },
  { key: "jumlah_lulusan", label: "Jumlah Lulusan", type: "integer" },
  { key: "jumlah_pengguna_tanggapan", label: "Pengguna Memberi Tanggapan", type: "integer" },
  { key: "jumlah_terlacak", label: "Jumlah Terlacak", type: "integer" },
  { key: "bekerja_lokal", label: "Lokal", type: "integer" },
  { key: "bekerja_nasional", label: "Nasional", type: "integer" },
  { key: "bekerja_multinasional", label: "Multinasional", type: "integer" },
];

const kepuasanPenggunaFields: FieldDefinition[] = [
  { key: "no", label: "No", type: "integer" },
  { key: "jenis_kemampuan", label: "Kemampuan", type: "text", span: 2 },
  { key: "sangat_baik", label: "Sangat Baik (%)", type: "decimal", step: 0.1 },
  { key: "baik", label: "Baik (%)", type: "decimal", step: 0.1 },
  { key: "cukup", label: "Cukup (%)", type: "decimal", step: 0.1 },
  { key: "kurang", label: "Kurang (%)", type: "decimal", step: 0.1 },
  { key: "rencana_tindak_lanjut", label: "Rencana Tindak Lanjut", type: "textarea", span: 2 },
];

const penelitianMahasiswaFields: FieldDefinition[] = [
  { key: "no", label: "No", type: "integer" },
  { key: "nama_dosen", label: "Nama Dosen", type: "text", span: 2 },
  { key: "tema_penelitian", label: "Tema Penelitian", type: "textarea", span: 2 },
  { key: "nama_mahasiswa", label: "Nama Mahasiswa", type: "text", span: 2 },
  { key: "judul_kegiatan", label: "Judul Kegiatan", type: "textarea", span: 2 },
  { key: "tahun", label: "Tahun", type: "integer" },
];

const spmiDokumenFields: FieldDefinition[] = [
  { key: "no", label: "No", type: "integer" },
  { key: "jenis_dokumen", label: "Jenis Dokumen", type: "textarea", span: 2 },
  { key: "no_dokumen", label: "Nomor Dokumen", type: "text" },
  { key: "tanggal_dokumen", label: "Tanggal", type: "date" },
];

const spmiPelaksanaanFields: FieldDefinition[] = [
  { key: "no", label: "No", type: "integer" },
  {
    key: "jenis_pelaksanaan",
    label: "Jenis",
    type: "select",
    options: [
      { label: "Penetapan", value: "Penetapan" },
      { label: "Pelaksanaan", value: "Pelaksanaan" },
      { label: "Evaluasi", value: "Evaluasi" },
      { label: "Pengendalian", value: "Pengendalian" },
      { label: "Peningkatan", value: "Peningkatan" },
    ],
  },
  { key: "link_dokumen", label: "Link Dokumen", type: "text", span: 2 },
  { key: "link_laporan_audit", label: "Link Audit", type: "text", span: 2 },
  { key: "link_laporan_rtm", label: "Link RTM", type: "text", span: 2 },
  { key: "link_dokumen_peningkatan", label: "Link Peningkatan", type: "text", span: 2 },
];

const staticSections: SectionDefinition[] = [
  {
    code: "PS",
    title: "Identitas Program Studi",
    sheetLabel: "Menu!A",
    purpose: "Data identitas PS diambil dari master Program Studi, pengisian hanya melalui modul master data.",
    group: "Menu",
    mode: "static",
    fields: [],
    note: "Gunakan modul 'Program Studi' untuk memperbarui data ini.",
  },
  {
    code: "PSPPI",
    title: "Profil Program Profesi Insinyur",
    sheetLabel: "PSPPI",
    purpose: "Disiplin teknik keinsinyuran yang diselenggarakan pada PPI.",
    group: "Menu",
    mode: "records",
    fields: pppiDisiplinFields,
    labelKey: "disiplin",
    templateRows: [
      { no: 1, disiplin: "Kebumian dan Energi" },
      { no: 2, disiplin: "Rekayasa Sipil dan Lingkungan Terbangun" },
      { no: 3, disiplin: "Industri" },
      { no: 4, disiplin: "Konservasi dan Pengelolaan Sumber Daya Alam" },
      { no: 5, disiplin: "Pertanian dan Hasil Pertanian" },
      { no: 6, disiplin: "Teknologi Kelautan dan Perkapalan" },
      { no: 7, disiplin: "Aeronotika dan Astronotika" },
    ],
    applicableFor: ["PPI"],
  },
  {
    code: "3a2",
    title: "Mata Kuliah PPI",
    sheetLabel: "3a2",
    purpose: "Mata kuliah dan dokumen pembelajaran PPI.",
    group: "Kriteria 3",
    mode: "records",
    fields: mataKuliahPpiFields,
    applicableFor: ["PPI"],
  },
];

export const LKPS_SECTIONS: SectionDefinition[] = [
  ...staticSections,
  {
    code: "1",
    title: "VMTS",
    sheetLabel: "1",
    purpose: "Mencatat visi, misi, tujuan, dan strategi pada level PT/UPPS/PS.",
    group: "Kriteria 1",
    mode: "records",
    fields: vmtsFields,
  },
  {
    code: "2a1",
    title: "Kerjasama Pendidikan",
    sheetLabel: "2a1",
    purpose: "Kerjasama tridharma bidang pendidikan.",
    group: "Kriteria 2",
    mode: "records",
    pinnedValues: { jenis: "pendidikan" },
    fields: kerjasamaFields,
  },
  {
    code: "2a2",
    title: "Kerjasama Penelitian",
    sheetLabel: "2a2",
    purpose: "Kerjasama tridharma bidang penelitian.",
    group: "Kriteria 2",
    mode: "records",
    pinnedValues: { jenis: "penelitian" },
    fields: kerjasamaFields,
  },
  {
    code: "2a3",
    title: "Kerjasama PKM",
    sheetLabel: "2a3",
    purpose: "Kerjasama tridharma bidang pengabdian pada masyarakat.",
    group: "Kriteria 2",
    mode: "records",
    pinnedValues: { jenis: "pkm" },
    fields: kerjasamaFields,
  },
  {
    code: "2b",
    title: "Penggunaan Dana",
    sheetLabel: "2b",
    purpose: "Distribusi penggunaan dana UPPS dan PS.",
    group: "Kriteria 2",
    mode: "records",
    fields: penggunaanDanaFields,
    labelKey: "kode",
    templateRows: [
      { kode: "biaya_dosen",              kode_label: "a. Biaya Dosen (Gaji, Honor)" },
      { kode: "biaya_tendik",             kode_label: "b. Biaya Tenaga Kependidikan (Gaji, Honor)" },
      { kode: "biaya_op_pembelajaran",    kode_label: "c. Biaya Operasional Pembelajaran (Bahan dan Peralatan Habis Pakai)" },
      { kode: "biaya_op_tidak_langsung",  kode_label: "d. Biaya Operasional Tidak Langsung (Listrik, Gas, Air, Pemeliharaan, dll.)" },
      { kode: "biaya_praktik_ppi",        kode_label: "e. Biaya Operasional Pendidikan di luar PT (Praktik Keinsinyuran, dll)" },
      { kode: "biaya_investasi",          kode_label: "f. Biaya Investasi (SDM, Sarana dan Prasarana)" },
      { kode: "biaya_kemahasiswaan",      kode_label: "Biaya Operasional Kemahasiswaan" },
      { kode: "biaya_penelitian",         kode_label: "Biaya Penelitian" },
      { kode: "biaya_pkm",               kode_label: "Biaya PkM" },
    ],
  },
  {
    code: "3a1",
    title: "Kurikulum",
    sheetLabel: "3a1",
    purpose: "Daftar mata kuliah dan beban belajar.",
    group: "Kriteria 3",
    mode: "records",
    fields: kurikulumFields,
  },
  {
    code: "3a3",
    title: "Integrasi Penelitian/PkM",
    sheetLabel: "3a3",
    purpose: "Integrasi hasil penelitian/PkM pada pembelajaran.",
    group: "Kriteria 3",
    mode: "records",
    fields: integrasiPenelitianFields,
  },
  {
    code: "3a4",
    title: "Basic Science",
    sheetLabel: "3a4",
    purpose: "Daftar MK basic science dan matematika.",
    group: "Kriteria 3",
    mode: "records",
    fields: basicScienceFields,
    applicableFor: ["S1", "S1Tr"],
  },
  {
    code: "3a5",
    title: "Capstone Design",
    sheetLabel: "3a5",
    purpose: "Rangkaian mata kuliah capstone design.",
    group: "Kriteria 3",
    mode: "records",
    fields: capstoneFields,
    applicableFor: ["S1", "S1Tr"],
  },
  {
    code: "3b",
    title: "Ringkasan Penelitian DTPS",
    sheetLabel: "3b",
    purpose: "Jumlah judul penelitian DTPS per sumber pembiayaan.",
    group: "Kriteria 3",
    mode: "records",
    fields: aggregateSummaryFields,
    labelKey: "kode_sumber",
    templateRows: [
      { kode_sumber: "perguruan_tinggi_mandiri", kode_label: "Perguruan Tinggi / Mandiri" },
      { kode_sumber: "dalam_negeri",             kode_label: "Lembaga Dalam Negeri" },
      { kode_sumber: "luar_negeri",              kode_label: "Lembaga Luar Negeri" },
    ],
  },
  {
    code: "3c",
    title: "Ringkasan PkM DTPS",
    sheetLabel: "3c",
    purpose: "Jumlah judul PkM DTPS per sumber pembiayaan.",
    group: "Kriteria 3",
    mode: "records",
    fields: aggregateSummaryFields,
    labelKey: "kode_sumber",
    templateRows: [
      { kode_sumber: "perguruan_tinggi_mandiri", kode_label: "Perguruan Tinggi / Mandiri" },
      { kode_sumber: "dalam_negeri",             kode_label: "Lembaga Dalam Negeri" },
      { kode_sumber: "luar_negeri",              kode_label: "Lembaga Luar Negeri" },
    ],
  },
  {
    code: "4a",
    title: "Profil DTPS",
    sheetLabel: "4a",
    purpose: "Data profil dosen tetap program studi.",
    group: "Kriteria 4",
    mode: "records",
    fields: dosenProfilFields,
  },
  {
    code: "4b",
    title: "Tenaga Kependidikan",
    sheetLabel: "4b",
    purpose: "Data laboran/teknisi/administrator.",
    group: "Kriteria 4",
    mode: "records",
    fields: tendikFields,
  },
  {
    code: "4c",
    title: "Beban Kerja Dosen",
    sheetLabel: "4c",
    purpose: "Beban kerja dosen tetap per jenis kegiatan.",
    group: "Kriteria 4",
    mode: "records",
    fields: bebanKerjaFields,
  },
  {
    code: "4d",
    title: "Publikasi DTPS (Akademik)",
    sheetLabel: "4d",
    purpose: "Publikasi ilmiah DTPS program akademik.",
    group: "Kriteria 4",
    mode: "records",
    pinnedValues: { sumber: "dtps", jenis_program: "akademik" },
    fields: publikasiFields,
    applicableFor: ["S1", "S2", "S3", "PPI"],
    labelKey: "kode_publikasi",
    templateRows: [
      { kode_publikasi: "jurnal_nasional_tidak_terakreditasi",     kode_label: "Jurnal Nasional Tidak Terakreditasi" },
      { kode_publikasi: "jurnal_nasional_terakreditasi",           kode_label: "Jurnal Nasional Terakreditasi" },
      { kode_publikasi: "jurnal_internasional",                    kode_label: "Jurnal Internasional" },
      { kode_publikasi: "jurnal_internasional_bereputasi",         kode_label: "Jurnal Internasional Bereputasi" },
      { kode_publikasi: "prosiding_nasional",                      kode_label: "Prosiding Nasional" },
      { kode_publikasi: "prosiding_internasional_tidak_terindeks", kode_label: "Prosiding Internasional Tidak Terindeks" },
      { kode_publikasi: "prosiding_internasional_terindeks",       kode_label: "Prosiding Internasional Terindeks" },
    ],
  },
  {
    code: "4e",
    title: "Publikasi DTPS (Vokasi)",
    sheetLabel: "4e",
    purpose: "Publikasi ilmiah DTPS program vokasi.",
    group: "Kriteria 4",
    mode: "records",
    pinnedValues: { sumber: "dtps", jenis_program: "vokasi" },
    fields: publikasiFields,
    applicableFor: ["D1", "D2", "D3", "S1Tr", "S2Tr", "S3Tr", "PPI"],
    labelKey: "kode_publikasi",
    templateRows: [
      { kode_publikasi: "jurnal_nasional_tidak_terakreditasi",     kode_label: "Jurnal Nasional Tidak Terakreditasi" },
      { kode_publikasi: "jurnal_nasional_terakreditasi",           kode_label: "Jurnal Nasional Terakreditasi" },
      { kode_publikasi: "jurnal_internasional",                    kode_label: "Jurnal Internasional" },
      { kode_publikasi: "jurnal_internasional_bereputasi",         kode_label: "Jurnal Internasional Bereputasi" },
      { kode_publikasi: "prosiding_nasional",                      kode_label: "Prosiding Nasional" },
      { kode_publikasi: "prosiding_internasional_tidak_terindeks", kode_label: "Prosiding Internasional Tidak Terindeks" },
      { kode_publikasi: "prosiding_internasional_terindeks",       kode_label: "Prosiding Internasional Terindeks" },
      { kode_publikasi: "pagelaran_wilayah",                       kode_label: "Pagelaran / Pameran / Presentasi Wilayah" },
      { kode_publikasi: "pagelaran_nasional",                      kode_label: "Pagelaran / Pameran / Presentasi Nasional" },
      { kode_publikasi: "pagelaran_internasional",                 kode_label: "Pagelaran / Pameran / Presentasi Internasional" },
    ],
  },
  {
    code: "4f-1",
    title: "Luaran DTPS - Paten",
    sheetLabel: "4f-1",
    purpose: "HKI kategori paten oleh DTPS.",
    group: "Kriteria 4",
    mode: "records",
    pinnedValues: { sumber: "dtps", jenis_luaran: "paten" },
    fields: luaranFields,
  },
  {
    code: "4f-2",
    title: "Luaran DTPS - Hak Cipta",
    sheetLabel: "4f-2",
    purpose: "HKI kategori hak cipta oleh DTPS.",
    group: "Kriteria 4",
    mode: "records",
    pinnedValues: { sumber: "dtps", jenis_luaran: "hak_cipta" },
    fields: luaranFields,
  },
  {
    code: "4f-3",
    title: "Luaran DTPS - Teknologi",
    sheetLabel: "4f-3",
    purpose: "Luaran teknologi oleh DTPS.",
    group: "Kriteria 4",
    mode: "records",
    pinnedValues: { sumber: "dtps", jenis_luaran: "teknologi" },
    fields: luaranFields,
  },
  {
    code: "4f-4",
    title: "Luaran DTPS - Buku",
    sheetLabel: "4f-4",
    purpose: "Buku ajar / referensi oleh DTPS.",
    group: "Kriteria 4",
    mode: "records",
    pinnedValues: { sumber: "dtps", jenis_luaran: "buku" },
    fields: luaranFields,
  },
  {
    code: "4g",
    title: "Produk/Jasa DTPS",
    sheetLabel: "4g",
    purpose: "Produk/jasa DTPS yang diadopsi industri/masyarakat.",
    group: "Kriteria 4",
    mode: "records",
    pinnedValues: { sumber: "dtps" },
    fields: produkJasaFields,
    applicableFor: ["D1", "D2", "D3", "S1Tr", "S2Tr", "S3Tr"],
  },
  {
    code: "4h",
    title: "Kinerja DTPS",
    sheetLabel: "4h",
    purpose: "Kinerja kompetitif DTPS.",
    group: "Kriteria 4",
    mode: "records",
    fields: [
      { key: "no", label: "No", type: "integer" },
      { key: "nama_dosen", label: "Nama Dosen", type: "text", span: 2 },
      { key: "ts2", label: "TS-2", type: "integer" },
      { key: "ts1", label: "TS-1", type: "integer" },
      { key: "ts", label: "TS", type: "integer" },
      { key: "keterangan", label: "Keterangan", type: "textarea", span: 2 },
    ],
    applicableFor: ["S1", "S1Tr", "S2", "S2Tr", "S3", "S3Tr"],
  },
  {
    code: "4i",
    title: "Sitasi DTPS",
    sheetLabel: "4i",
    purpose: "Karya ilmiah DTPS yang disitasi.",
    group: "Kriteria 4",
    mode: "records",
    fields: [
      { key: "no", label: "No", type: "integer" },
      { key: "nama_dosen", label: "Nama Dosen", type: "text", span: 2 },
      { key: "judul_artikel", label: "Judul Artikel", type: "textarea", span: 2 },
      { key: "jumlah_sitasi", label: "Jumlah Sitasi", type: "integer" },
    ],
    applicableFor: ["S1", "S1Tr", "S2", "S2Tr", "S3", "S3Tr"],
  },
  {
    code: "4j",
    title: "Rekognisi DTPS",
    sheetLabel: "4j",
    purpose: "Rekognisi/penghargaan DTPS.",
    group: "Kriteria 4",
    mode: "records",
    fields: rekognisiFields,
  },
  {
    code: "4k",
    title: "Pembimbing Lapangan",
    sheetLabel: "4k",
    purpose: "Pembimbing lapangan PPI.",
    group: "Kriteria 4",
    mode: "records",
    fields: pembimbingFields,
    applicableFor: ["PPI"],
  },
  {
    code: "5a",
    title: "Prasarana",
    sheetLabel: "5a",
    purpose: "Inventaris prasarana & sarana.",
    group: "Kriteria 5",
    mode: "records",
    fields: prasaranaFields,
  },
  {
    code: "5b",
    title: "Dokumen K3L",
    sheetLabel: "5b",
    purpose: "Ketersediaan dokumen K3L.",
    group: "Kriteria 5",
    mode: "records",
    fields: k3lDokumenFields,
  },
  {
    code: "5c",
    title: "Fasilitas K3L",
    sheetLabel: "5c",
    purpose: "Fasilitas keselamatan kesehatan kerja.",
    group: "Kriteria 5",
    mode: "records",
    fields: k3lFasilitasFields,
  },
  {
    code: "6a",
    title: "Mahasiswa Aktif",
    sheetLabel: "6a",
    purpose: "Jumlah mahasiswa aktif & asing.",
    group: "Kriteria 6",
    mode: "records",
    fields: mahasiswaAktifFields,
  },
  {
    code: "6b",
    title: "IPK Lulusan",
    sheetLabel: "6b",
    purpose: "IPK lulusan TS-2 s.d TS.",
    group: "Kriteria 6",
    mode: "records",
    fields: ipkFields,
  },
  {
    code: "6c1",
    title: "Prestasi Akademik",
    sheetLabel: "6c1",
    purpose: "Prestasi akademik mahasiswa.",
    group: "Kriteria 6",
    mode: "records",
    pinnedValues: { jenis: "akademik" },
    fields: prestasiFields,
    applicableFor: ["D1", "D2", "D3", "S1", "S1Tr", "S2", "S2Tr", "S3", "S3Tr"],
  },
  {
    code: "6c2",
    title: "Prestasi Non-Akademik",
    sheetLabel: "6c2",
    purpose: "Prestasi non-akademik mahasiswa.",
    group: "Kriteria 6",
    mode: "records",
    pinnedValues: { jenis: "non_akademik" },
    fields: prestasiFields,
    applicableFor: ["D1", "D2", "D3", "S1", "S1Tr"],
  },
  {
    code: "6d",
    title: "Masa Studi",
    sheetLabel: "6d",
    purpose: "Masa studi per jenis program.",
    group: "Kriteria 6",
    mode: "records",
    fields: masaStudiFields,
  },
  {
    code: "6e1",
    title: "Publikasi Mahasiswa (Akademik)",
    sheetLabel: "6e1",
    purpose: "Publikasi mahasiswa program akademik.",
    group: "Kriteria 6",
    mode: "records",
    pinnedValues: { sumber: "mahasiswa", jenis_program: "akademik" },
    fields: publikasiFields,
    applicableFor: ["S1", "S2", "S3"],
  },
  {
    code: "6e2",
    title: "Publikasi Mahasiswa (Vokasi)",
    sheetLabel: "6e2",
    purpose: "Publikasi mahasiswa program vokasi.",
    group: "Kriteria 6",
    mode: "records",
    pinnedValues: { sumber: "mahasiswa", jenis_program: "vokasi" },
    fields: publikasiFields,
    applicableFor: ["S1Tr", "S2Tr", "S3Tr"],
  },
  {
    code: "6e3-1",
    title: "Luaran Mahasiswa - Paten",
    sheetLabel: "6e3-1",
    purpose: "Luaran mahasiswa kategori paten.",
    group: "Kriteria 6",
    mode: "records",
    pinnedValues: { sumber: "mahasiswa", jenis_luaran: "paten" },
    fields: luaranFields,
  },
  {
    code: "6e3-2",
    title: "Luaran Mahasiswa - Hak Cipta",
    sheetLabel: "6e3-2",
    purpose: "Luaran mahasiswa kategori hak cipta.",
    group: "Kriteria 6",
    mode: "records",
    pinnedValues: { sumber: "mahasiswa", jenis_luaran: "hak_cipta" },
    fields: luaranFields,
  },
  {
    code: "6e3-3",
    title: "Luaran Mahasiswa - Teknologi",
    sheetLabel: "6e3-3",
    purpose: "Luaran mahasiswa kategori teknologi.",
    group: "Kriteria 6",
    mode: "records",
    pinnedValues: { sumber: "mahasiswa", jenis_luaran: "teknologi" },
    fields: luaranFields,
  },
  {
    code: "6e3-4",
    title: "Luaran Mahasiswa - Buku",
    sheetLabel: "6e3-4",
    purpose: "Buku karya mahasiswa.",
    group: "Kriteria 6",
    mode: "records",
    pinnedValues: { sumber: "mahasiswa", jenis_luaran: "buku" },
    fields: luaranFields,
  },
  {
    code: "6e4",
    title: "Produk/Jasa Mahasiswa",
    sheetLabel: "6e4",
    purpose: "Produk/jasa mahasiswa yang diadopsi pasar.",
    group: "Kriteria 6",
    mode: "records",
    pinnedValues: { sumber: "mahasiswa" },
    fields: produkJasaFields,
    applicableFor: ["D1", "D2", "D3", "S1Tr", "S2Tr", "S3Tr"],
  },
  {
    code: "6f1",
    title: "Waktu Tunggu Lulusan",
    sheetLabel: "6f1",
    purpose: "Waktu tunggu memperoleh pekerjaan.",
    group: "Kriteria 6",
    mode: "records",
    fields: waktuTungguFields,
    applicableFor: ["D1", "D2", "D3", "S1", "S1Tr", "PPI"],
  },
  {
    code: "6f2",
    title: "Kesesuaian Bidang Kerja",
    sheetLabel: "6f2",
    purpose: "Kesesuaian kerja lulusan.",
    group: "Kriteria 6",
    mode: "records",
    fields: kesesuaianKerjaFields,
    applicableFor: ["D1", "D2", "D3", "S1", "S1Tr", "S2", "S2Tr"],
  },
  {
    code: "6g1",
    title: "Tempat Kerja",
    sheetLabel: "6g1",
    purpose: "Level kerja lulusan.",
    group: "Kriteria 6",
    mode: "records",
    fields: tempatKerjaFields,
    applicableFor: ["D1", "D2", "D3", "S1", "S1Tr", "S2", "S2Tr", "PPI"],
  },
  {
    code: "6g2",
    title: "Kepuasan Pengguna",
    sheetLabel: "6g2",
    purpose: "Penilaian pengguna lulusan.",
    group: "Kriteria 6",
    mode: "records",
    fields: kepuasanPenggunaFields,
    applicableFor: ["D1", "D2", "D3", "S1", "S1Tr", "S2", "S2Tr", "PPI"],
  },
  {
    code: "6h1",
    title: "Penelitian bersama Mahasiswa",
    sheetLabel: "6h1",
    purpose: "Penelitian DTPS melibatkan mahasiswa.",
    group: "Kriteria 6",
    mode: "records",
    pinnedValues: { jenis: "penelitian" },
    fields: penelitianMahasiswaFields,
    applicableFor: ["S1", "S1Tr", "S2", "S2Tr", "S3", "S3Tr", "PPI"],
  },
  {
    code: "6h2",
    title: "Tesis/Disertasi",
    sheetLabel: "6h2",
    purpose: "Tesis/disertasi yang melibatkan mahasiswa.",
    group: "Kriteria 6",
    mode: "records",
    pinnedValues: { jenis: "tesis_disertasi" },
    fields: penelitianMahasiswaFields,
    applicableFor: ["S2", "S2Tr", "S3", "S3Tr"],
  },
  {
    code: "6i",
    title: "PkM melibatkan Mahasiswa",
    sheetLabel: "6i",
    purpose: "Kegiatan PkM DTPS melibatkan mahasiswa.",
    group: "Kriteria 6",
    mode: "records",
    pinnedValues: { jenis: "pkm" },
    fields: penelitianMahasiswaFields,
  },
  {
    code: "7a",
    title: "SPMI Dokumen",
    sheetLabel: "7a",
    purpose: "Ketersediaan dokumen SPMI.",
    group: "Kriteria 7",
    mode: "records",
    fields: spmiDokumenFields,
    labelKey: "jenis_dokumen",
    templateRows: [
      { jenis_dokumen: "Kebijakan SPMI",                             kode_label: "Kebijakan SPMI" },
      { jenis_dokumen: "Pedoman penerapan siklus PPEPP standar pendidikan tinggi dalam SPMI", kode_label: "Pedoman penerapan siklus PPEPP standar pendidikan tinggi dalam SPMI" },
      { jenis_dokumen: "Standar dan/atau kriteria, norma, acuan mutu penyelenggaraan pendidikan dan pengelolaan perguruan tinggi", kode_label: "Standar dan/atau kriteria, norma, acuan mutu penyelenggaraan pendidikan dan pengelolaan perguruan tinggi" },
      { jenis_dokumen: "Tata cara pendokumentasian implementasi SPMI", kode_label: "Tata cara pendokumentasian implementasi SPMI" },
    ],
  },
  {
    code: "7b",
    title: "SPMI Pelaksanaan",
    sheetLabel: "7b",
    purpose: "Pelaksanaan PPEPP dan tindak lanjut.",
    group: "Kriteria 7",
    mode: "records",
    fields: spmiPelaksanaanFields,
    labelKey: "jenis_pelaksanaan",
    templateRows: [
      { jenis_pelaksanaan: "Penetapan",    kode_label: "Penetapan" },
      { jenis_pelaksanaan: "Pelaksanaan",  kode_label: "Pelaksanaan" },
      { jenis_pelaksanaan: "Evaluasi",     kode_label: "Evaluasi" },
      { jenis_pelaksanaan: "Pengendalian", kode_label: "Pengendalian" },
      { jenis_pelaksanaan: "Peningkatan",  kode_label: "Peningkatan" },
    ],
  },
];
