import type { Metadata } from "next";
import { Inria_Serif } from "next/font/google";
import "./globals.css";
import ConditionalNavbar from "./components/navigation/ConditionalNavbar";

const inriaSerif = Inria_Serif({
  variable: "--font-inria-serif",
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inriaSerif.variable} font-sans antialiased`}>
        <ConditionalNavbar />
        {children}
      </body>
    </html>
  );
}
