"""add dashboard models

Revision ID: 59b11e9f1ed7
Revises: ec7f9ad03f45
Create Date: 2026-04-02 12:16:47.072506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59b11e9f1ed7'
down_revision: Union[str, None] = 'ec7f9ad03f45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kriteria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kode', sa.String(length=20), nullable=False),
    sa.Column('nama', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode')
    )
    op.create_table('indikator',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kriteria_id', sa.UUID(), nullable=False),
    sa.Column('kode_indikator', sa.String(length=50), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=False),
    sa.Column('tipe_input', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['kriteria_id'], ['kriteria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('target_akreditasi',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('program_studi_id', sa.UUID(), nullable=False),
    sa.Column('tahun_akreditasi', sa.Integer(), nullable=False),
    sa.Column('target_skor', sa.Float(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('notifikasi_aktif', sa.Boolean(), nullable=True),
    sa.Column('is_aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['program_studi_id'], ['program_studi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_lkps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_akreditasi_id', sa.UUID(), nullable=False),
    sa.Column('indikator_id', sa.UUID(), nullable=False),
    sa.Column('nilai_capaian', sa.Float(), nullable=True),
    sa.Column('status_validasi', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['indikator_id'], ['indikator.id'], ),
    sa.ForeignKeyConstraint(['target_akreditasi_id'], ['target_akreditasi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('narasi_led',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_akreditasi_id', sa.UUID(), nullable=False),
    sa.Column('indikator_id', sa.UUID(), nullable=False),
    sa.Column('narasi', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['indikator_id'], ['indikator.id'], ),
    sa.ForeignKeyConstraint(['target_akreditasi_id'], ['target_akreditasi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('indikator_id', sa.UUID(), nullable=True),
    sa.Column('narasi_led_id', sa.UUID(), nullable=True),
    sa.Column('nama_file', sa.String(length=255), nullable=False),
    sa.Column('url_file', sa.String(length=500), nullable=False),
    sa.Column('tipe_file', sa.String(length=50), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['indikator_id'], ['indikator.id'], ),
    sa.ForeignKeyConstraint(['narasi_led_id'], ['narasi_led.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence')
    op.drop_table('narasi_led')
    op.drop_table('data_lkps')
    op.drop_table('target_akreditasi')
    op.drop_table('indikator')
    op.drop_table('kriteria')
    # ### end Alembic commands ###
