"""refactor evidence model

Revision ID: 7145d4e24792
Revises: 59b11e9f1ed7
Create Date: 2026-04-02 18:47:04.777847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7145d4e24792'
down_revision: Union[str, None] = '59b11e9f1ed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_indikator',
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('indikator_id', sa.UUID(), nullable=False),
    sa.Column('target_akreditasi_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['indikator_id'], ['indikator.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_akreditasi_id'], ['target_akreditasi.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evidence_id', 'indikator_id')
    )
    op.create_table('evidence_prodi',
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('prodi_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prodi_id'], ['program_studi.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evidence_id', 'prodi_id')
    )
    op.add_column('evidence', sa.Column('judul', sa.String(length=255), nullable=False))
    op.add_column('evidence', sa.Column('deskripsi', sa.Text(), nullable=True))
    op.add_column('evidence', sa.Column('is_global', sa.Boolean(), nullable=False))
    op.add_column('evidence', sa.Column('uploaded_by', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('evidence_indikator_id_fkey'), 'evidence', type_='foreignkey')
    op.drop_constraint(op.f('evidence_narasi_led_id_fkey'), 'evidence', type_='foreignkey')
    op.create_foreign_key(None, 'evidence', 'users', ['uploaded_by'], ['id'])
    op.drop_column('evidence', 'indikator_id')
    op.drop_column('evidence', 'narasi_led_id')
    op.drop_column('evidence', 'nama_file')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence', sa.Column('nama_file', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('evidence', sa.Column('narasi_led_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('evidence', sa.Column('indikator_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'evidence', type_='foreignkey')
    op.create_foreign_key(op.f('evidence_narasi_led_id_fkey'), 'evidence', 'narasi_led', ['narasi_led_id'], ['id'])
    op.create_foreign_key(op.f('evidence_indikator_id_fkey'), 'evidence', 'indikator', ['indikator_id'], ['id'])
    op.drop_column('evidence', 'uploaded_by')
    op.drop_column('evidence', 'is_global')
    op.drop_column('evidence', 'deskripsi')
    op.drop_column('evidence', 'judul')
    op.drop_table('evidence_prodi')
    op.drop_table('evidence_indikator')
    # ### end Alembic commands ###
