"""empty message

Revision ID: 76346ee080cc
Revises: ec7f9ad03f45
Create Date: 2026-04-02 02:38:25.054995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76346ee080cc'
down_revision: Union[str, None] = 'ec7f9ad03f45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('criteria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_criteria',
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('criteria', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['criteria'], ['criteria.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('evidence_id', 'criteria')
    )
    op.create_table('evidence_prodi',
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('prodi_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['prodi_id'], ['program_studi.id'], ),
    sa.PrimaryKeyConstraint('evidence_id', 'prodi_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence_prodi')
    op.drop_table('evidence_criteria')
    op.drop_table('evidence')
    op.drop_table('criteria')
    # ### end Alembic commands ###
