"""add_simulasi_tables

Revision ID: e0fc705b4cfc
Revises: e5f6a7b8c9d0
Create Date: 2026-05-09 09:49:21.820657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0fc705b4cfc'
down_revision: Union[str, None] = 'e5f6a7b8c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matriks_akreditasi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lembaga', sa.String(), nullable=True),
    sa.Column('jenjang', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matriks_akreditasi_id'), 'matriks_akreditasi', ['id'], unique=False)
    op.create_index(op.f('ix_matriks_akreditasi_jenjang'), 'matriks_akreditasi', ['jenjang'], unique=False)
    op.create_index(op.f('ix_matriks_akreditasi_lembaga'), 'matriks_akreditasi', ['lembaga'], unique=False)
    op.create_table('komponen_penilaian',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matriks_id', sa.Integer(), nullable=True),
    sa.Column('nama', sa.String(), nullable=True),
    sa.Column('bobot', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['matriks_id'], ['matriks_akreditasi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_komponen_penilaian_id'), 'komponen_penilaian', ['id'], unique=False)
    op.create_table('indikator_simulasi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('komponen_id', sa.Integer(), nullable=True),
    sa.Column('kode_indikator', sa.String(), nullable=True),
    sa.Column('nama_indikator', sa.String(), nullable=True),
    sa.Column('tipe_evaluasi', sa.String(), nullable=True),
    sa.Column('konfigurasi_rumus', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['komponen_id'], ['komponen_penilaian.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indikator_simulasi_id'), 'indikator_simulasi', ['id'], unique=False)
    op.drop_constraint(op.f('lkps_beban_kerja_dosen_submission_id_fkey'), 'lkps_beban_kerja_dosen', type_='foreignkey')
    op.create_foreign_key(None, 'lkps_beban_kerja_dosen', 'lkps_submission', ['submission_id'], ['id'])
    op.drop_constraint(op.f('lkps_capstone_design_submission_id_fkey'), 'lkps_capstone_design', type_='foreignkey')
    op.create_foreign_key(None, 'lkps_capstone_design', 'lkps_submission', ['submission_id'], ['id'])
    op.drop_constraint(op.f('lkps_dosen_profil_submission_id_fkey'), 'lkps_dosen_profil', type_='foreignkey')
    op.create_foreign_key(None, 'lkps_dosen_profil', 'lkps_submission', ['submission_id'], ['id'])
    op.drop_constraint(op.f('lkps_integrasi_penelitian_submission_id_fkey'), 'lkps_integrasi_penelitian', type_='foreignkey')
    op.create_foreign_key(None, 'lkps_integrasi_penelitian', 'lkps_submission', ['submission_id'], ['id'])
    op.drop_constraint(op.f('lkps_ipk_lulusan_submission_id_fkey'), 'lkps_ipk_lulusan', type_='foreignkey')
    op.create_foreign_key(None, 'lkps_ipk_lulusan', 'lkps_submission', ['submission_id'], ['id'])
    op.drop_constraint(op.f('lkps_k3l_dokumen_submission_id_fkey'), 'lkps_k3l_dokumen', type_='foreignkey')
    op.create_foreign_key(None, 'lkps_k3l_dokumen', 'lkps_submission', ['submission_id'], ['id'])
    op.drop_constraint(op.f('lkps_k3l_fasilitas_submission_id_fkey'), 'lkps_k3l_fasilitas', type_='foreignkey')
    op.create_foreign_key(None, 'lkps_k3l_fasilitas', 'lkps_submission', ['submission_id'], ['id'])
    op.drop_constraint(op.f('lkps_kepuasan_pengguna_submission_id_fkey'), 'lkps_kepuasan_pengguna', type_='foreignkey')
    op.create_foreign_key(None, 'lkps_kepuasan_pengguna', 'lkps_submission', ['submission_id'], ['id'])
    op.drop_constraint(op.f('lkps_kerjasama_submission_id_fkey'), 'lkps_kerjasama', type_='foreignkey')
    op.create_foreign_key(None, 'lkps_kerjasama', 'lkps_submission', ['submission_id'], ['id'])
    op.drop_constraint(op.f('lkps_kesesuaian_kerja_submission_id_fkey'), 'lkps_kesesuaian_kerja', type_='foreignkey')
    op.create_foreign_key(None, 'lkps_kesesuaian_kerja', 'lkps_submission', ['submission_id'], ['id'])
    op.drop_constraint(op.f('lkps_kinerja_dtps_submission_id_fkey'), 'lkps_kinerja_dtps', type_='foreignkey')
    op.create_foreign_key(None, 'lkps_kinerja_dtps', 'lkps_submission', ['submission_id'], ['id'])
    op.drop_constraint(op.f('lkps_kurikulum_submission_id_fkey'), 'lkps_kurikulum', type_='foreignkey')
    op.create_foreign_key(None, 'lkps_kurikulum', 'lkps_submission', ['submission_id'], ['id'])
    op.drop_constraint(op.f('lkps_luaran_penelitian_submission_id_fkey'), 'lkps_luaran_penelitian', type_='foreignkey')
    op.create_foreign_key(None, 'lkps_luaran_penelitian', 'lkps_submission', ['submission_id'], ['id'])
    op.drop_constraint(op.f('lkps_mahasiswa_aktif_submission_id_fkey'), 'lkps_mahasiswa_aktif', type_='foreignkey')
    op.create_foreign_key(None, 'lkps_mahasiswa_aktif', 'lkps_submission', ['submission_id'], ['id'])
    op.drop_constraint(op.f('lkps_masa_studi_submission_id_fkey'), 'lkps_masa_studi', type_='foreignkey')
    op.create_foreign_key(None, 'lkps_masa_studi', 'lkps_submission', ['submission_id'], ['id'])
    op.drop_constraint(op.f('lkps_mk_basic_science_submission_id_fkey'), 'lkps_mk_basic_science', type_='foreignkey')
    op.create_foreign_key(None, 'lkps_mk_basic_science', 'lkps_submission', ['submission_id'], ['id'])
    op.drop_constraint(op.f('lkps_pembimbing_lapangan_submission_id_fkey'), 'lkps_pembimbing_lapangan', type_='foreignkey')
    op.create_foreign_key(None, 'lkps_pembimbing_lapangan', 'lkps_submission', ['submission_id'], ['id'])
    op.drop_constraint(op.f('lkps_penelitian_mahasiswa_submission_id_fkey'), 'lkps_penelitian_mahasiswa', type_='foreignkey')
    op.create_foreign_key(None, 'lkps_penelitian_mahasiswa', 'lkps_submission', ['submission_id'], ['id'])
    op.drop_constraint(op.f('lkps_penelitian_summary_submission_id_fkey'), 'lkps_penelitian_summary', type_='foreignkey')
    op.create_foreign_key(None, 'lkps_penelitian_summary', 'lkps_submission', ['submission_id'], ['id'])
    op.drop_constraint(op.f('lkps_penggunaan_dana_submission_id_fkey'), 'lkps_penggunaan_dana', type_='foreignkey')
    op.create_foreign_key(None, 'lkps_penggunaan_dana', 'lkps_submission', ['submission_id'], ['id'])
    op.drop_constraint(op.f('lkps_pkm_summary_submission_id_fkey'), 'lkps_pkm_summary', type_='foreignkey')
    op.create_foreign_key(None, 'lkps_pkm_summary', 'lkps_submission', ['submission_id'], ['id'])
    op.drop_constraint(op.f('lkps_prasarana_submission_id_fkey'), 'lkps_prasarana', type_='foreignkey')
    op.create_foreign_key(None, 'lkps_prasarana', 'lkps_submission', ['submission_id'], ['id'])
    op.drop_constraint(op.f('lkps_prestasi_mahasiswa_submission_id_fkey'), 'lkps_prestasi_mahasiswa', type_='foreignkey')
    op.create_foreign_key(None, 'lkps_prestasi_mahasiswa', 'lkps_submission', ['submission_id'], ['id'])
    op.drop_constraint(op.f('lkps_produk_jasa_submission_id_fkey'), 'lkps_produk_jasa', type_='foreignkey')
    op.create_foreign_key(None, 'lkps_produk_jasa', 'lkps_submission', ['submission_id'], ['id'])
    op.drop_constraint(op.f('lkps_publikasi_ilmiah_submission_id_fkey'), 'lkps_publikasi_ilmiah', type_='foreignkey')
    op.create_foreign_key(None, 'lkps_publikasi_ilmiah', 'lkps_submission', ['submission_id'], ['id'])
    op.drop_constraint(op.f('lkps_rekognisi_dtps_submission_id_fkey'), 'lkps_rekognisi_dtps', type_='foreignkey')
    op.create_foreign_key(None, 'lkps_rekognisi_dtps', 'lkps_submission', ['submission_id'], ['id'])
    op.drop_constraint(op.f('lkps_section_progress_submission_id_fkey'), 'lkps_section_progress', type_='foreignkey')
    op.create_foreign_key(None, 'lkps_section_progress', 'lkps_submission', ['submission_id'], ['id'])
    op.drop_constraint(op.f('lkps_sitasi_dtps_submission_id_fkey'), 'lkps_sitasi_dtps', type_='foreignkey')
    op.create_foreign_key(None, 'lkps_sitasi_dtps', 'lkps_submission', ['submission_id'], ['id'])
    op.drop_constraint(op.f('lkps_spmi_dokumen_submission_id_fkey'), 'lkps_spmi_dokumen', type_='foreignkey')
    op.create_foreign_key(None, 'lkps_spmi_dokumen', 'lkps_submission', ['submission_id'], ['id'])
    op.drop_constraint(op.f('lkps_spmi_pelaksanaan_submission_id_fkey'), 'lkps_spmi_pelaksanaan', type_='foreignkey')
    op.create_foreign_key(None, 'lkps_spmi_pelaksanaan', 'lkps_submission', ['submission_id'], ['id'])
    op.drop_constraint(op.f('lkps_tempat_kerja_submission_id_fkey'), 'lkps_tempat_kerja', type_='foreignkey')
    op.create_foreign_key(None, 'lkps_tempat_kerja', 'lkps_submission', ['submission_id'], ['id'])
    op.drop_constraint(op.f('lkps_tenaga_kependidikan_submission_id_fkey'), 'lkps_tenaga_kependidikan', type_='foreignkey')
    op.create_foreign_key(None, 'lkps_tenaga_kependidikan', 'lkps_submission', ['submission_id'], ['id'])
    op.alter_column('lkps_vmts', 'no',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('lkps_vmts_submission_id_fkey'), 'lkps_vmts', type_='foreignkey')
    op.create_foreign_key(None, 'lkps_vmts', 'lkps_submission', ['submission_id'], ['id'])
    op.drop_constraint(op.f('lkps_waktu_tunggu_submission_id_fkey'), 'lkps_waktu_tunggu', type_='foreignkey')
    op.create_foreign_key(None, 'lkps_waktu_tunggu', 'lkps_submission', ['submission_id'], ['id'])
    op.alter_column('narasi_led', 'narasi',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(op.f('uq_narasi_led_target_indikator'), 'narasi_led', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_narasi_led_target_indikator'), 'narasi_led', ['target_akreditasi_id', 'indikator_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('narasi_led', 'narasi',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(None, 'lkps_waktu_tunggu', type_='foreignkey')
    op.create_foreign_key(op.f('lkps_waktu_tunggu_submission_id_fkey'), 'lkps_waktu_tunggu', 'lkps_submission', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lkps_vmts', type_='foreignkey')
    op.create_foreign_key(op.f('lkps_vmts_submission_id_fkey'), 'lkps_vmts', 'lkps_submission', ['submission_id'], ['id'], ondelete='CASCADE')
    op.alter_column('lkps_vmts', 'no',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'lkps_tenaga_kependidikan', type_='foreignkey')
    op.create_foreign_key(op.f('lkps_tenaga_kependidikan_submission_id_fkey'), 'lkps_tenaga_kependidikan', 'lkps_submission', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lkps_tempat_kerja', type_='foreignkey')
    op.create_foreign_key(op.f('lkps_tempat_kerja_submission_id_fkey'), 'lkps_tempat_kerja', 'lkps_submission', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lkps_spmi_pelaksanaan', type_='foreignkey')
    op.create_foreign_key(op.f('lkps_spmi_pelaksanaan_submission_id_fkey'), 'lkps_spmi_pelaksanaan', 'lkps_submission', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lkps_spmi_dokumen', type_='foreignkey')
    op.create_foreign_key(op.f('lkps_spmi_dokumen_submission_id_fkey'), 'lkps_spmi_dokumen', 'lkps_submission', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lkps_sitasi_dtps', type_='foreignkey')
    op.create_foreign_key(op.f('lkps_sitasi_dtps_submission_id_fkey'), 'lkps_sitasi_dtps', 'lkps_submission', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lkps_section_progress', type_='foreignkey')
    op.create_foreign_key(op.f('lkps_section_progress_submission_id_fkey'), 'lkps_section_progress', 'lkps_submission', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lkps_rekognisi_dtps', type_='foreignkey')
    op.create_foreign_key(op.f('lkps_rekognisi_dtps_submission_id_fkey'), 'lkps_rekognisi_dtps', 'lkps_submission', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lkps_publikasi_ilmiah', type_='foreignkey')
    op.create_foreign_key(op.f('lkps_publikasi_ilmiah_submission_id_fkey'), 'lkps_publikasi_ilmiah', 'lkps_submission', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lkps_produk_jasa', type_='foreignkey')
    op.create_foreign_key(op.f('lkps_produk_jasa_submission_id_fkey'), 'lkps_produk_jasa', 'lkps_submission', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lkps_prestasi_mahasiswa', type_='foreignkey')
    op.create_foreign_key(op.f('lkps_prestasi_mahasiswa_submission_id_fkey'), 'lkps_prestasi_mahasiswa', 'lkps_submission', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lkps_prasarana', type_='foreignkey')
    op.create_foreign_key(op.f('lkps_prasarana_submission_id_fkey'), 'lkps_prasarana', 'lkps_submission', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lkps_pkm_summary', type_='foreignkey')
    op.create_foreign_key(op.f('lkps_pkm_summary_submission_id_fkey'), 'lkps_pkm_summary', 'lkps_submission', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lkps_penggunaan_dana', type_='foreignkey')
    op.create_foreign_key(op.f('lkps_penggunaan_dana_submission_id_fkey'), 'lkps_penggunaan_dana', 'lkps_submission', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lkps_penelitian_summary', type_='foreignkey')
    op.create_foreign_key(op.f('lkps_penelitian_summary_submission_id_fkey'), 'lkps_penelitian_summary', 'lkps_submission', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lkps_penelitian_mahasiswa', type_='foreignkey')
    op.create_foreign_key(op.f('lkps_penelitian_mahasiswa_submission_id_fkey'), 'lkps_penelitian_mahasiswa', 'lkps_submission', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lkps_pembimbing_lapangan', type_='foreignkey')
    op.create_foreign_key(op.f('lkps_pembimbing_lapangan_submission_id_fkey'), 'lkps_pembimbing_lapangan', 'lkps_submission', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lkps_mk_basic_science', type_='foreignkey')
    op.create_foreign_key(op.f('lkps_mk_basic_science_submission_id_fkey'), 'lkps_mk_basic_science', 'lkps_submission', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lkps_masa_studi', type_='foreignkey')
    op.create_foreign_key(op.f('lkps_masa_studi_submission_id_fkey'), 'lkps_masa_studi', 'lkps_submission', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lkps_mahasiswa_aktif', type_='foreignkey')
    op.create_foreign_key(op.f('lkps_mahasiswa_aktif_submission_id_fkey'), 'lkps_mahasiswa_aktif', 'lkps_submission', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lkps_luaran_penelitian', type_='foreignkey')
    op.create_foreign_key(op.f('lkps_luaran_penelitian_submission_id_fkey'), 'lkps_luaran_penelitian', 'lkps_submission', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lkps_kurikulum', type_='foreignkey')
    op.create_foreign_key(op.f('lkps_kurikulum_submission_id_fkey'), 'lkps_kurikulum', 'lkps_submission', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lkps_kinerja_dtps', type_='foreignkey')
    op.create_foreign_key(op.f('lkps_kinerja_dtps_submission_id_fkey'), 'lkps_kinerja_dtps', 'lkps_submission', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lkps_kesesuaian_kerja', type_='foreignkey')
    op.create_foreign_key(op.f('lkps_kesesuaian_kerja_submission_id_fkey'), 'lkps_kesesuaian_kerja', 'lkps_submission', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lkps_kerjasama', type_='foreignkey')
    op.create_foreign_key(op.f('lkps_kerjasama_submission_id_fkey'), 'lkps_kerjasama', 'lkps_submission', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lkps_kepuasan_pengguna', type_='foreignkey')
    op.create_foreign_key(op.f('lkps_kepuasan_pengguna_submission_id_fkey'), 'lkps_kepuasan_pengguna', 'lkps_submission', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lkps_k3l_fasilitas', type_='foreignkey')
    op.create_foreign_key(op.f('lkps_k3l_fasilitas_submission_id_fkey'), 'lkps_k3l_fasilitas', 'lkps_submission', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lkps_k3l_dokumen', type_='foreignkey')
    op.create_foreign_key(op.f('lkps_k3l_dokumen_submission_id_fkey'), 'lkps_k3l_dokumen', 'lkps_submission', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lkps_ipk_lulusan', type_='foreignkey')
    op.create_foreign_key(op.f('lkps_ipk_lulusan_submission_id_fkey'), 'lkps_ipk_lulusan', 'lkps_submission', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lkps_integrasi_penelitian', type_='foreignkey')
    op.create_foreign_key(op.f('lkps_integrasi_penelitian_submission_id_fkey'), 'lkps_integrasi_penelitian', 'lkps_submission', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lkps_dosen_profil', type_='foreignkey')
    op.create_foreign_key(op.f('lkps_dosen_profil_submission_id_fkey'), 'lkps_dosen_profil', 'lkps_submission', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lkps_capstone_design', type_='foreignkey')
    op.create_foreign_key(op.f('lkps_capstone_design_submission_id_fkey'), 'lkps_capstone_design', 'lkps_submission', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lkps_beban_kerja_dosen', type_='foreignkey')
    op.create_foreign_key(op.f('lkps_beban_kerja_dosen_submission_id_fkey'), 'lkps_beban_kerja_dosen', 'lkps_submission', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_indikator_simulasi_id'), table_name='indikator_simulasi')
    op.drop_table('indikator_simulasi')
    op.drop_index(op.f('ix_komponen_penilaian_id'), table_name='komponen_penilaian')
    op.drop_table('komponen_penilaian')
    op.drop_index(op.f('ix_matriks_akreditasi_lembaga'), table_name='matriks_akreditasi')
    op.drop_index(op.f('ix_matriks_akreditasi_jenjang'), table_name='matriks_akreditasi')
    op.drop_index(op.f('ix_matriks_akreditasi_id'), table_name='matriks_akreditasi')
    op.drop_table('matriks_akreditasi')
    # ### end Alembic commands ###
